spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:vps-database.cpngyolgpjfp.us-east-1.rds.amazonaws.com}:${DB_PORT:5432}/${DB_NAME:db_vps_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:150948Vi!}
  jpa:
    hibernate:
      ddl-auto: validate

cors:
  allowed:
    origins: ${CORS_HOST:http://localhost:3000}
    all-methods: true
    all-headers: true
    send-credentials: true